/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutUs: typeof import('./components/aboutUs/index.vue')['default']
    AddMusic: typeof import('./components/addMusic/index.vue')['default']
    Drawer: typeof import('./components/drawer/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IEpChromeFilled: typeof import('~icons/ep/chrome-filled')['default']
    IEpComment: typeof import('~icons/ep/comment')['default']
    IEpDownload: typeof import('~icons/ep/download')['default']
    IEpElementPlus: typeof import('~icons/ep/element-plus')['default']
    IEpPromotion: typeof import('~icons/ep/promotion')['default']
    IEpQuestionFilled: typeof import('~icons/ep/question-filled')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpShare: typeof import('~icons/ep/share')['default']
    IEpStar: typeof import('~icons/ep/star')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IEpVideoPause: typeof import('~icons/ep/video-pause')['default']
    IEpVideoPlay: typeof import('~icons/ep/video-play')['default']
    Index: typeof import('./components/index/index.vue')['default']
    Mine: typeof import('./components/mine/mine.vue')['default']
    ModifyCombo: typeof import('./components/modifyCombo/index.vue')['default']
    ModifyMusic: typeof import('./components/modifyMusic/index.vue')['default']
    MusicComment: typeof import('./components/musicComment/index.vue')['default']
    MusicList: typeof import('./components/musicList/index.vue')['default']
    MusicMange: typeof import('./components/musicMange/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopIn: typeof import('./components/top-in/index.vue')['default']
    UserMange: typeof import('./components/userMange/userMange.vue')['default']
    Vip: typeof import('./components/vip/index.vue')['default']
  }
}
